#!/bin/bash

# ═══════════════════════════════════════════════════════════════════════════
# Frontend + Backend Startup Script
# ═══════════════════════════════════════════════════════════════════════════
# 
# This script shows you exactly how to start both servers and run tests
# 
# ═══════════════════════════════════════════════════════════════════════════

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                    Frontend Testing Setup                     ║"
echo "║                                                                ║"
echo "║  This shows you how to start your servers and run tests      ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 STEP 1: Prepare Environment"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Before you start, you need to know:"
echo "  1. What port is your BACKEND API running on?"
echo "     Common ports: 3001, 8080, 5000, 8000"
echo ""
echo "  2. Do you have test users in your backend?"
echo "     Email: admin@example.com"
echo "     Password: password123"
echo "     Role: admin"
echo ""
echo "Ask your team if you're not sure!"
echo ""

echo ""
echo "📋 STEP 2: Update .env File"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Edit: .env"
echo ""
echo "Change this line to match your backend port:"
echo "  API_BASE_URL=http://localhost:YOUR_BACKEND_PORT"
echo ""
echo "Examples:"
echo "  API_BASE_URL=http://localhost:3001    # Default"
echo "  API_BASE_URL=http://localhost:8080    # Common alternative"
echo "  API_BASE_URL=http://localhost:5000    # Flask/Python"
echo ""

echo ""
echo "📋 STEP 3: Terminal 1 - Start Backend"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "In your BACKEND repository directory, run:"
echo ""
echo "  $ npm run dev"
echo ""
echo "You should see output like:"
echo "  ✓ Server running on port 3001"
echo "  ✓ Connected to database"
echo ""
echo "Leave this terminal running!"
echo ""

echo ""
echo "📋 STEP 4: Terminal 2 - Verify Backend is Accessible"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "In a NEW terminal, test the backend:"
echo ""
echo "  $ curl http://localhost:YOUR_BACKEND_PORT/jobs"
echo ""
echo "If successful, you'll see JSON with job data"
echo "If it fails, your backend isn't running on that port"
echo ""

echo ""
echo "📋 STEP 5: Terminal 3 - Start Frontend"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "In the FRONTEND directory (team4-job-app-frontend), run:"
echo ""
echo "  $ npm run dev"
echo ""
echo "You should see:"
echo "  ✓ Tailwind CSS built"
echo "  ✓ TypeScript compiled"
echo "  ✓ Server is running on http://localhost:3000"
echo ""
echo "Leave this terminal running!"
echo ""

echo ""
echo "📋 STEP 6: Verify Frontend Loads"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "In your browser, open:"
echo "  http://localhost:3000"
echo ""
echo "You should see the job application homepage"
echo "If you see errors, check:"
echo "  - Browser console (F12)"
echo "  - Terminal output above"
echo "  - .env API_BASE_URL is correct"
echo ""

echo ""
echo "📋 STEP 7: Terminal 4 - Run Playwright Tests"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "In ANOTHER NEW terminal in the FRONTEND directory, run:"
echo ""
echo "  $ npm run test:pw:ui"
echo ""
echo "This will:"
echo "  ✅ Open Playwright Inspector"
echo "  ✅ Show tests running in a real browser"
echo "  ✅ Let you debug failures in real-time"
echo ""
echo "Alternatively, run headless (background):"
echo "  $ npm run test:pw"
echo ""
echo "Or run a specific test:"
echo "  $ npx playwright test tests/e2e/adminlogin.spec.ts"
echo ""

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "✅ ALL SET!"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Summary of what's running:"
echo "  - Terminal 1: Backend on localhost:YOUR_BACKEND_PORT"
echo "  - Terminal 3: Frontend on http://localhost:3000"
echo "  - Terminal 4: Playwright tests"
echo ""
echo "If something doesn't work:"
echo "  1. Check browser console (F12) for errors"
echo "  2. Check terminal output for error messages"
echo "  3. Run: bash diagnose.sh"
echo "  4. Read: COMPLETE_FIX_GUIDE.md"
echo ""
echo "🎉 Good luck with your tests!"
echo ""
